import 'package:injectify/injectify.dart';
import 'package:shared/app_config.dart';

/// Own registration generated by the root app's `injection.config.dart`.\n///
/// Its constructor parameter [AppConfig] lives in the `shared` package,
/// showing that the root app's generated code resolves cross-package
/// dependencies as long as the provider package was initialized first.
@Injectable(scope: Scope.lazySingleton)
class StartupService {
  final AppConfig _config;

  StartupService(this._config);

  String banner() => '${_config.appName} v${_config.version} ready';
}

@Injectable(scope: Scope.lazySingleton)
class RootDemoService {
  final AppConfig _config;

  RootDemoService(this._config);

  String hello() => '${_config.appName} v${_config.version} -- hello';
}
