targets:
  $default:
    builders:
      injectable_codegen:injectable_builder:
        options:
          # Automatically uses relative imports when possible
          prefer_relative_imports: true
          # Default initializer name
          initializer_name: 'init'
