/// References a [MicroPackageModule] type from ANOTHER package (own pubspec)
/// to be composed by this package's generated initializer.
///
/// These modules live outside this package's scan boundary (e.g. a module
/// generated by another pubspec in the same monorepo), so they cannot be
/// auto-discovered. Declaring them here makes the generated `init()` call
/// `gh.initMicroPackage(TypeName())` in declaration order.
///
/// The referenced module class must have a default (const-free) constructor,
/// like every generated `XInjectableModule`.
///
/// Difference from [InjectableInit.modules]: `modules` filters modules
/// DISCOVERED inside this package's own scan, while `externalMicroPackages`
/// composes module types that exist in other packages.
class ExternalMicroPackage {
  /// The generated module class type (e.g. `SharedInjectableModule`).
  final Type moduleType;

  /// Creates an [ExternalMicroPackage] reference.
  const ExternalMicroPackage(this.moduleType);
}

/// Annotation to mark the root initialization point for dependency injection code generation.
class InjectableInit {
  /// The name of the generated initialization method/extension.
  final String initializerName;

  /// Whether to prefer relative imports over package imports in generated code.
  final bool preferRelativeImports;

  /// Whether to generate the initialization function as an extension on [GetIt].
  final bool asExtension;

  /// The directories to scan for injectable classes.
  final List<String> generateForDir;

  /// Whether to enable micro-package support.
  final bool useMicroPackage;

  /// Sub-modules / micro-package modules to compose in this root module.
  final List<Type> modules;

  /// External micro-package module types (from other packages with their own
  /// pubspec) to compose in declaration order alongside discovered modules.
  final List<ExternalMicroPackage> externalMicroPackages;

  /// Optional module/micro-package name (e.g. 'App', 'Auth', 'Orders').
  final String? moduleName;

  /// Custom class name for the generated module class (e.g. 'AppInjectableModule').
  final String? moduleClassName;

  /// Whether to allow registering multiple instances/dependencies without throw.
  final bool? allowMultipleRegistrations;

  /// Creates an [InjectableInit] annotation.
  const InjectableInit({
    this.initializerName = 'init',
    this.preferRelativeImports = true,
    this.asExtension = true,
    this.generateForDir = const ['lib'],
    this.useMicroPackage = false,
    this.modules = const [],
    this.externalMicroPackages = const [],
    this.moduleName,
    this.moduleClassName,
    this.allowMultipleRegistrations,
  });

  /// Creates an [InjectableInit] configured specifically for a micro-package / sub-module.
  const InjectableInit.microPackage({
    this.initializerName = 'init',
    this.preferRelativeImports = true,
    this.asExtension = true,
    this.generateForDir = const ['lib'],
    this.useMicroPackage = true,
    this.modules = const [],
    this.externalMicroPackages = const [],
    this.moduleName,
    this.moduleClassName,
    this.allowMultipleRegistrations,
  });
}

/// Annotation to mark a feature directory or sub-module as an isolated micro-package.
///
/// Example:
/// ```dart
/// @InjectableMicroPackage(moduleName: 'Auth')
/// void configureAuthModule() {}
/// ```
///
/// With [useMicroPackage] set to `true`, the generated `XInjectableModule`
/// automatically composes every nested sub micro-package discovered inside this
/// folder (boundary isolation still applies — the sub folders are excluded from
/// this module's own dependency scan, but their generated modules are registered
/// via `gh.initMicroPackage(...)` inside this module's `init()`).
///
/// Compose each module exactly once: either the parent module composes a nested
/// sub-module with `useMicroPackage: true`, or the app/root composes it
/// explicitly — not both, or GetIt throws on double registration.
class InjectableMicroPackage extends InjectableInit {
  /// Creates an [InjectableMicroPackage] annotation.
  const InjectableMicroPackage({
    super.initializerName = 'init',
    super.preferRelativeImports = true,
    super.asExtension = true,
    super.generateForDir = const ['lib'],
    super.useMicroPackage = false,
    super.modules = const [],
    super.externalMicroPackages = const [],
    super.moduleName,
    super.moduleClassName,
    super.allowMultipleRegistrations,
  }) : super.microPackage();
}
